### ISSUE TITLE
Firefox Private Window displays empty audio and video drop-downs

### ISSUE THREAD

**Issue by hectoroso** [voxeet/voxeet-uxkit-react#131] opened 2021-08-18 23:23 UTC
**Describe the bug**

In Firefox Private Window, the audio and video drop-downs are empty in the `ConferencePreConfigContainer`. 
They are not empty in the Settings tab. 
Also, this does not happen in a regular Firefox window.

https://webrtc.github.io/samples/src/content/devices/input-output/ works fine in Firefox Private Window.

**Expected Behaviour**

Drop-downs list devices.

**Steps to Reproduce the Problem**

  1. git clone https://github.com/voxeet/voxeet-uxkit-react.git (commit a8f6b3217cbdec732914a1ead898b61acb95032d)
  2. npm install 
  3. npm start
  4. Open https://127.0.0.1:4444/ 
  5. Allow access to devices

**Minimalistic code (recommended)**

This repo.

**Specifications**

  - Device: MacBook Pro
  - OS: MacOS 11.5.1
  - Platform: Firefox 91.0
  - Subsystem: Private Browser

  - Version: 
    - "@voxeet/voxeet-web-sdk": "^3.2.1"
    - "@voxeet/react-components": "^3.2.1",
    - "react": "16.9.0"
    - Node v14.17.5
  - Hardware:
    - FaceTime HD Camera (Built-in)
    - MacBook Pro Microphone

<img width="609" alt="Screen Shot 2021-08-18 at 4 10 11 PM" src="https://user-images.githubusercontent.com/660786/129984451-9e69f7a3-f4d7-40d2-826c-8f27176c76b4.png">
<img width="338" alt="Screen Shot 2021-08-18 at 4 10 31 PM" src="https://user-images.githubusercontent.com/660786/129984456-0d906949-fe96-4778-9553-7035115432d1.png">

**Comment by FabienLavocat** [comment] 2021-08-18 23:32
@Energizz similar to Safari, before calling the enumerateDevices(), we need to call getUserMedia(), otherwise the device labels are not returned.

**Comment by FabienLavocat** [comment] 2022-08-02 04:12
The issue is being fixed by this commit: https://github.com/voxeet/voxeet-uxkit-react/pull/240/commits/e88b3775d53ef7d6e94cddeebc5540e51a5326e4

**Closed** 2023-02-24 02:13 UTC
Labels: bug
